/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bug;

import Models.BugM;
import Models.UserM;
import User.User;
import java.awt.Image;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.SessionStorage;

/**
 *
 * @author ahmed
 */
public class BugsListJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BugJFrame
     */
    public BugsListJFrame() {
        initComponents();
        checkAuth();
        initTable();
    }

    private static void removeAllRows() {
        int RowSize = jTable1.getRowCount();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < RowSize; i++) {
            model.removeRow(0);
        }

    }

    public static void initTable() {

        removeAllRows();

        BugM bm = new BugM();
        ResultSet rs;
        User userData = ((User) SessionStorage.getData());

        javax.swing.JTable jTableProjects = project.ProjectsListJFrame.jTable1;

        int sRow = jTableProjects.getSelectedRow();

        int projectId = (int) jTableProjects.getValueAt(sRow, 0);

        try {
            switch (userData.getRole()) {
                case "Developer": {
                    rs = bm.get("developer_id=" + userData.getID() + " AND project_id=" + projectId);
                    break;
                }
                default: {
                    rs = bm.get("project_id=" + projectId);
                }
            }

            while (rs.next()) {
                addTableRow(rs);
            }
            rs.close();
            bm.statement.close();
        } catch (Exception e) {

            messages.JFrameMessage.showErr(e);
        }

    }

    public static void addTableRow(ResultSet rs) throws SQLException, IOException {
        UserM u = new UserM();

        String devName = "";
        String testerName = "";

        ResultSet userRs = u.get("id=" + rs.getInt("developer_id"));

        if (userRs.next()) {
            devName = userRs.getString("name");
        }

        userRs = u.get("id=" + rs.getInt("tester_id"));

        if (userRs.next()) {
            testerName = userRs.getString("name");
        }
        
        if(userRs.getInt("id") == ((User) SessionStorage.getData()).getID()) testerName = "You";

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[]{rs.getInt("id"), rs.getString("name"), rs.getString("type"), rs.getString("priority"), rs.getString("level"), devName, testerName, rs.getString("date"), rs.getString("img"), rs.getBoolean("status")});

        userRs.close();
    }

    private void checkAuth() {
        User u = ((User) SessionStorage.getData());

        switch (u.getRole()) {
            case "Tester": {
                jPanel2.remove(chStatBtn);
                break;
            }
            case "Developer": {
                jPanel2.remove(creatBtn);
                jPanel2.remove(updateBtn);
                break;
            }
            default: {
                jPanel2.removeAll();
                jPanel1.remove(jPanel2);
            }
        }
        revalidate();
        repaint();
    }

    ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        creatBtn = new javax.swing.JButton();
        chStatBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bugs");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Type", "Priority", "Level", "Dveloper", "Tester", "Date", "Photo", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        creatBtn.setText("Create");
        creatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatBtnMouseClicked(evt);
            }
        });
        creatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatBtnActionPerformed(evt);
            }
        });

        chStatBtn.setText("Change status");
        chStatBtn.setEnabled(false);
        chStatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chStatBtnMouseClicked(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.setEnabled(false);
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(chStatBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creatBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateBtn)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creatBtn)
                    .addComponent(chStatBtn)
                    .addComponent(updateBtn))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void creatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creatBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 1) {
            if (chStatBtn.getParent() != null) {
                chStatBtn.setEnabled(true);
            }
            if (updateBtn.getParent() != null) {
                updateBtn.setEnabled(true);
            }
        } else if (evt.getClickCount() == 2) {

            String imagePath = "Images\\" + (String) jTable1.getValueAt(jTable1.getSelectedRow(), 8);

            ImageIcon originalIcon = new ImageIcon(imagePath);

            Image originalImage = originalIcon.getImage();
            
            System.out.println(originalImage);

            Image scaledImage = originalImage.getScaledInstance(300, 200, Image.SCALE_SMOOTH);

            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            JOptionPane.showMessageDialog(null, scaledIcon, "Image Viewer", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void creatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatBtnMouseClicked

        new bugJframe(null).setVisible(true);
        ;

    }//GEN-LAST:event_creatBtnMouseClicked

    private void chStatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chStatBtnMouseClicked
        if (chStatBtn.isEnabled()) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int sRow = jTable1.getSelectedRow();
            int bugId = (int) jTable1.getValueAt(sRow, 0);
            boolean bugStatus = (boolean) jTable1.getValueAt(sRow, 9);

            BugM bm = new BugM();

            try {
                bm.update("status = " + !bugStatus, "id=" + bugId);
                jTable1.setValueAt(!bugStatus, sRow, 9);
            } catch (Exception e) {
                messages.JFrameMessage.showErr(e);
            }
        }
    }//GEN-LAST:event_chStatBtnMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int sRow = jTable1.getSelectedRow();

        if (sRow == -1) {
            return;
        }

        int bugId = (int) jTable1.getValueAt(sRow, 0);

        int devId;

        BugM bm = new BugM();

        try {
            ResultSet rs = bm.getById(bugId);

            rs.next();
            
            if(rs.getInt("tester_id") != ((User) SessionStorage.getData()).getID()){
                updateBtn.setEnabled(false);
                return;
            }

            devId = rs.getInt("developer_id");

            new bugJframe(rs).setVisible(true);

        } catch (Exception e) {
            messages.JFrameMessage.showErr(e);
        }
    }//GEN-LAST:event_updateBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BugsListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BugsListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BugsListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BugsListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BugsListJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chStatBtn;
    private javax.swing.JButton creatBtn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
